/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardArRouteImport } from './routes/dashboard.ar'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardRestaurantRouteImport } from './routes/dashboard.restaurant'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as TTokenIndexRouteImport } from './routes/t.$token.index'
import { Route as TTokenArDishIdRouteImport } from './routes/t.$token.ar.$dishId'
import { Route as TTokenDishDishIdRouteImport } from './routes/t.$token.dish.$dishId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArRoute = DashboardArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRestaurantRoute = DashboardRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenIndexRoute = TTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTokenRoute,
} as any)
const TTokenArDishIdRoute = TTokenArDishIdRouteImport.update({
  id: '/ar/$dishId',
  path: '/ar/$dishId',
  getParentRoute: () => TTokenRoute,
} as any)
const TTokenDishDishIdRoute = TTokenDishDishIdRouteImport.update({
  id: '/dish/$dishId',
  path: '/dish/$dishId',
  getParentRoute: () => TTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ar': typeof DashboardArRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/t/$token': typeof TTokenRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/t/$token/': typeof TTokenIndexRoute
  '/t/$token/ar/$dishId': typeof TTokenArDishIdRoute
  '/t/$token/dish/$dishId': typeof TTokenDishDishIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ar': typeof DashboardArRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/t/$token': typeof TTokenIndexRoute
  '/t/$token/ar/$dishId': typeof TTokenArDishIdRoute
  '/t/$token/dish/$dishId': typeof TTokenDishDishIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ar': typeof DashboardArRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/t/$token': typeof TTokenRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/t/$token/': typeof TTokenIndexRoute
  '/t/$token/ar/$dishId': typeof TTokenArDishIdRoute
  '/t/$token/dish/$dishId': typeof TTokenDishDishIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/ar'
    | '/dashboard/menu'
    | '/dashboard/restaurant'
    | '/dashboard/settings'
    | '/t/$token'
    | '/dashboard/'
    | '/t/$token/'
    | '/t/$token/ar/$dishId'
    | '/t/$token/dish/$dishId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/ar'
    | '/dashboard/menu'
    | '/dashboard/restaurant'
    | '/dashboard/settings'
    | '/dashboard'
    | '/t/$token'
    | '/t/$token/ar/$dishId'
    | '/t/$token/dish/$dishId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/ar'
    | '/dashboard/menu'
    | '/dashboard/restaurant'
    | '/dashboard/settings'
    | '/t/$token'
    | '/dashboard/'
    | '/t/$token/'
    | '/t/$token/ar/$dishId'
    | '/t/$token/dish/$dishId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TTokenRoute: typeof TTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ar': {
      id: '/dashboard/ar'
      path: '/ar'
      fullPath: '/dashboard/ar'
      preLoaderRoute: typeof DashboardArRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/restaurant': {
      id: '/dashboard/restaurant'
      path: '/restaurant'
      fullPath: '/dashboard/restaurant'
      preLoaderRoute: typeof DashboardRestaurantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token/': {
      id: '/t/$token/'
      path: '/'
      fullPath: '/t/$token/'
      preLoaderRoute: typeof TTokenIndexRouteImport
      parentRoute: typeof TTokenRoute
    }
    '/t/$token/ar/$dishId': {
      id: '/t/$token/ar/$dishId'
      path: '/ar/$dishId'
      fullPath: '/t/$token/ar/$dishId'
      preLoaderRoute: typeof TTokenArDishIdRouteImport
      parentRoute: typeof TTokenRoute
    }
    '/t/$token/dish/$dishId': {
      id: '/t/$token/dish/$dishId'
      path: '/dish/$dishId'
      fullPath: '/t/$token/dish/$dishId'
      preLoaderRoute: typeof TTokenDishDishIdRouteImport
      parentRoute: typeof TTokenRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardArRoute: typeof DashboardArRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardRestaurantRoute: typeof DashboardRestaurantRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArRoute: DashboardArRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardRestaurantRoute: DashboardRestaurantRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TTokenRouteChildren {
  TTokenIndexRoute: typeof TTokenIndexRoute
  TTokenArDishIdRoute: typeof TTokenArDishIdRoute
  TTokenDishDishIdRoute: typeof TTokenDishDishIdRoute
}

const TTokenRouteChildren: TTokenRouteChildren = {
  TTokenIndexRoute: TTokenIndexRoute,
  TTokenArDishIdRoute: TTokenArDishIdRoute,
  TTokenDishDishIdRoute: TTokenDishDishIdRoute,
}

const TTokenRouteWithChildren =
  TTokenRoute._addFileChildren(TTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TTokenRoute: TTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
